import type { NavigationModule } from '../types/navigation'

export const NAVIGATION_MODULES: NavigationModule[] = [
  {
    id: 'eventos',
    title: 'EVENTOS',
    iconName: 'CalendarDays',
    path: '/eventos',
    badge: '12',
    badgeColor: 'blue',
    description: 'Gestão de eventos, sessões, locais, lotes, capacidade e check-in',
    subItems: [
      { title: 'Dashboard de Eventos', path: '/eventos' },
      { title: 'Todos os Eventos', path: '/eventos/lista' },
      { title: 'Criar Evento', path: '/eventos/novo' },
      { title: 'Configuração', path: '/eventos/configuracao' },
      { title: 'Datas e Sessões', path: '/eventos/sessoes' },
      { title: 'Locais', path: '/eventos/locais' },
      { title: 'Setores', path: '/eventos/setores' },
      { title: 'Mapa de Assentos', path: '/eventos/mapa-assentos' },
      { title: 'Tipos de Ingresso', path: '/eventos/tipos-ingresso' },
      { title: 'Lotes', path: '/eventos/lotes' },
      { title: 'Preços', path: '/eventos/precos' },
      { title: 'Meia-entrada', path: '/eventos/meia-entrada' },
      { title: 'Cortesias', path: '/eventos/cortesias' },
      { title: 'Convites', path: '/eventos/convites' },
      { title: 'Reservas', path: '/eventos/reservas' },
      { title: 'Canais de Venda', path: '/eventos/canais' },
      { title: 'PDV', path: '/eventos/pdv' },
      { title: 'Bilheteria', path: '/eventos/bilheteria' },
      { title: 'Check-in', path: '/eventos/check-in', badge: 'Ao vivo', badgeColor: 'emerald' },
      { title: 'Participantes', path: '/eventos/participantes' },
      { title: 'Capacidade', path: '/eventos/capacidade' },
      { title: 'Equipe', path: '/eventos/equipe' },
      { title: 'Credenciamento', path: '/eventos/credenciamento' },
      { title: 'Documentos', path: '/eventos/documentos' },
      { title: 'Termos', path: '/eventos/termos' },
      { title: 'Integrações', path: '/eventos/integracoes' },
      { title: 'Relatórios', path: '/eventos/relatorios' },
    ],
  },
  {
    id: 'comercial',
    title: 'COMERCIAL',
    iconName: 'TrendingUp',
    path: '/comercial',
    badge: 'R$ 7.4M',
    badgeColor: 'emerald',
    description: 'Centro de receita, pedidos em tempo real, canais e metas',
    subItems: [
      { title: 'Dashboard Comercial', path: '/comercial' },
      { title: 'Vendas em Tempo Real', path: '/comercial/tempo-real', badge: 'Ao vivo', badgeColor: 'emerald' },
      { title: 'Pedidos', path: '/comercial/pedidos' },
      { title: 'Ingressos', path: '/comercial/ingressos' },
      { title: 'Clientes', path: '/comercial/clientes' },
      { title: 'Produtores', path: '/comercial/produtores' },
      { title: 'PDVs', path: '/comercial/pdvs' },
      { title: 'Bilheterias', path: '/comercial/bilheterias' },
      { title: 'Canais de Venda', path: '/comercial/canais' },
      { title: 'Vendedores', path: '/comercial/vendedores' },
      { title: 'Parceiros', path: '/comercial/parceiros' },
      { title: 'Afiliados', path: '/comercial/afiliados' },
      { title: 'Cupons', path: '/comercial/cupons' },
      { title: 'Cortesias', path: '/comercial/cortesias' },
      { title: 'Reservas', path: '/comercial/reservas' },
      { title: 'Funil Comercial', path: '/comercial/funil' },
      { title: 'Metas', path: '/comercial/metas' },
      { title: 'Performance', path: '/comercial/performance' },
      { title: 'Ticket Médio', path: '/comercial/ticket-medio' },
      { title: 'Conversão', path: '/comercial/conversao' },
      { title: 'Comparativo de Eventos', path: '/comercial/comparativo' },
      { title: 'Previsão de Vendas', path: '/comercial/previsao' },
      { title: 'Relatórios Comerciais', path: '/comercial/relatorios' },
    ],
  },
  {
    id: 'suporte-eventos',
    title: 'SUPORTE EVENTOS',
    iconName: 'Headphones',
    path: '/suporte-eventos',
    badge: '3 Ativos',
    badgeColor: 'amber',
    description: 'Suporte a produtores, modo evento em tempo real e bilheterias',
    subItems: [
      { title: 'Central Operacional', path: '/suporte-eventos' },
      { title: 'Modo Evento (Ao Vivo)', path: '/suporte-eventos/modo-evento', badge: 'Ao vivo', badgeColor: 'emerald' },
      { title: 'Eventos em Operação', path: '/suporte-eventos/em-operacao' },
      { title: 'Chamados', path: '/suporte-eventos/chamados', badge: '4', badgeColor: 'rose' },
      { title: 'Incidentes', path: '/suporte-eventos/incidentes' },
      { title: 'Problemas', path: '/suporte-eventos/problemas' },
      { title: 'Check-in', path: '/suporte-eventos/check-in' },
      { title: 'Bilheteria', path: '/suporte-eventos/bilheteria' },
      { title: 'PDVs', path: '/suporte-eventos/pdvs' },
      { title: 'Impressoras', path: '/suporte-eventos/impressoras' },
      { title: 'Leitores', path: '/suporte-eventos/leitores' },
      { title: 'Equipes', path: '/suporte-eventos/equipes' },
      { title: 'Filas', path: '/suporte-eventos/filas' },
      { title: 'SLA', path: '/suporte-eventos/sla' },
      { title: 'Escalonamento', path: '/suporte-eventos/escalonamento' },
      { title: 'Ocorrências', path: '/suporte-eventos/ocorrencias' },
      { title: 'Alertas', path: '/suporte-eventos/alertas' },
      { title: 'Histórico', path: '/suporte-eventos/historico' },
      { title: 'Base de Conhecimento', path: '/suporte-eventos/base-conhecimento' },
      { title: 'Relatórios', path: '/suporte-eventos/relatorios' },
    ],
  },
  {
    id: 'sac',
    title: 'ATENDIMENTO SAC',
    iconName: 'MessageSquareText',
    path: '/sac',
    badge: '18',
    badgeColor: 'blue',
    description: 'Atendimento ao cliente comprador com busca unificada por CPF e pedido',
    subItems: [
      { title: 'Dashboard SAC', path: '/sac' },
      { title: 'Central de Atendimento', path: '/sac/central' },
      { title: 'Consulta de Clientes', path: '/sac/consulta', badge: 'Universal', badgeColor: 'blue' },
      { title: 'Tickets', path: '/sac/tickets' },
      { title: 'Caixa de Entrada', path: '/sac/inbox' },
      { title: 'WhatsApp', path: '/sac/whatsapp' },
      { title: 'E-mail', path: '/sac/email' },
      { title: 'Chat', path: '/sac/chat' },
      { title: 'Pedidos', path: '/sac/pedidos' },
      { title: 'Ingressos', path: '/sac/ingressos' },
      { title: 'Clientes', path: '/sac/clientes' },
      { title: 'Histórico', path: '/sac/historico' },
      { title: 'Filas', path: '/sac/filas' },
      { title: 'Agentes', path: '/sac/agentes' },
      { title: 'SLA', path: '/sac/sla' },
      { title: 'Respostas Rápidas', path: '/sac/respostas-rapidas' },
      { title: 'Base de Conhecimento', path: '/sac/base-conhecimento' },
      { title: 'Automações', path: '/sac/automacoes' },
      { title: 'CSAT', path: '/sac/csat' },
      { title: 'NPS', path: '/sac/nps' },
      { title: 'Relatórios', path: '/sac/relatorios' },
    ],
  },
  {
    id: 'estorno',
    title: 'ESTORNO',
    iconName: 'RotateCcw',
    path: '/estorno',
    badge: '5 Pend.',
    badgeColor: 'amber',
    description: 'Gestão de reembolsos, chargebacks, cancelamentos e auditoria financeira',
    subItems: [
      { title: 'Dashboard de Estorno', path: '/estorno' },
      { title: 'Solicitações', path: '/estorno/solicitacoes', badge: '5', badgeColor: 'amber' },
      { title: 'Nova Solicitação', path: '/estorno/nova' },
      { title: 'Em Análise', path: '/estorno/analise' },
      { title: 'Aguardando Aprovação', path: '/estorno/aguardando-aprovacao' },
      { title: 'Aprovados', path: '/estorno/aprovados' },
      { title: 'Rejeitados', path: '/estorno/rejeitados' },
      { title: 'Processados', path: '/estorno/processados' },
      { title: 'Falhas', path: '/estorno/falhas' },
      { title: 'Estorno Parcial', path: '/estorno/parcial' },
      { title: 'Estorno Total', path: '/estorno/total' },
      { title: 'Cancelamentos', path: '/estorno/cancelamentos' },
      { title: 'Chargebacks', path: '/estorno/chargebacks', badge: 'Alerta', badgeColor: 'rose' },
      { title: 'Contestação', path: '/estorno/contestacao' },
      { title: 'Gateways', path: '/estorno/gateways' },
      { title: 'Regras', path: '/estorno/regras' },
      { title: 'Aprovações', path: '/estorno/aprovacoes' },
      { title: 'Auditoria', path: '/estorno/auditoria' },
      { title: 'Relatórios', path: '/estorno/relatorios' },
    ],
  },
  {
    id: 'financeiro',
    title: 'FINANCEIRO',
    iconName: 'DollarSign',
    path: '/financeiro',
    badge: 'R$ 4.2M',
    badgeColor: 'emerald',
    description: 'Saldos segregados por evento, repasses a produtores e tesouraria',
    subItems: [
      { title: 'Dashboard Financeiro', path: '/financeiro' },
      { title: 'Conta do Produtor', path: '/financeiro/conta-produtor' },
      { title: 'Saldos por Evento', path: '/financeiro/saldos-evento' },
      { title: 'Transferência entre Eventos', path: '/financeiro/transferencias' },
      { title: 'Contas a Receber', path: '/financeiro/contas-receber' },
      { title: 'Contas a Pagar', path: '/financeiro/contas-pagar' },
      { title: 'Centro de Custos', path: '/financeiro/centro-custos' },
      { title: 'Repasses', path: '/financeiro/repasses' },
      { title: 'Antecipações', path: '/financeiro/antecipacoes' },
      { title: 'Conciliação', path: '/financeiro/conciliacao' },
      { title: 'Tesouraria', path: '/financeiro/tesouraria' },
      { title: 'Contas Bancárias', path: '/financeiro/contas-bancarias' },
      { title: 'PIX', path: '/financeiro/pix' },
      { title: 'CNAB', path: '/financeiro/cnab' },
      { title: 'Pagamentos', path: '/financeiro/pagamentos' },
      { title: 'Taxas', path: '/financeiro/taxas' },
      { title: 'Gateways', path: '/financeiro/gateways' },
      { title: 'Fornecedores', path: '/financeiro/fornecedores' },
      { title: 'Compras', path: '/financeiro/compras' },
      { title: 'Contratos', path: '/financeiro/contratos' },
      { title: 'Fluxo de Caixa', path: '/financeiro/fluxo-caixa' },
      { title: 'DRE Gerencial', path: '/financeiro/dre-gerencial' },
      { title: 'Projeções', path: '/financeiro/projecoes' },
      { title: 'Agenda Financeira', path: '/financeiro/agenda' },
      { title: 'Relatórios', path: '/financeiro/relatorios' },
      { title: 'Auditoria', path: '/financeiro/auditoria' },
    ],
  },
  {
    id: 'contabilidade',
    title: 'CONTABILIDADE',
    iconName: 'FileSpreadsheet',
    path: '/contabilidade',
    badge: 'Fechamento',
    badgeColor: 'blue',
    description: 'Segregação contábil rigorosa: Receita DiskIngressos vs Valores de Produtores',
    subItems: [
      { title: 'Dashboard Contábil', path: '/contabilidade' },
      { title: 'Plano de Contas', path: '/contabilidade/plano-contas' },
      { title: 'Lançamentos', path: '/contabilidade/lancamentos' },
      { title: 'Livro Razão', path: '/contabilidade/livro-razao' },
      { title: 'Livro Diário', path: '/contabilidade/livro-diario' },
      { title: 'Centros de Resultado', path: '/contabilidade/centros-resultado' },
      { title: 'Conciliação Contábil', path: '/contabilidade/conciliacao' },
      { title: 'Receita da Plataforma', path: '/contabilidade/receita-plataforma' },
      { title: 'Valores de Produtores', path: '/contabilidade/valores-produtores' },
      { title: 'Receita Diferida', path: '/contabilidade/receita-diferida' },
      { title: 'Taxas', path: '/contabilidade/taxas' },
      { title: 'Repasses', path: '/contabilidade/repasses' },
      { title: 'Competência', path: '/contabilidade/competencia' },
      { title: 'DRE', path: '/contabilidade/dre' },
      { title: 'Balanço Patrimonial', path: '/contabilidade/balanco' },
      { title: 'Balancete', path: '/contabilidade/balancete' },
      { title: 'Fluxo Contábil', path: '/contabilidade/fluxo-contabil' },
      { title: 'Documentos', path: '/contabilidade/documentos' },
      { title: 'Fiscal', path: '/contabilidade/fiscal' },
      { title: 'Fechamento', path: '/contabilidade/fechamento' },
      { title: 'Auditoria', path: '/contabilidade/auditoria' },
      { title: 'Compliance', path: '/contabilidade/compliance' },
      { title: 'Relatórios', path: '/contabilidade/relatorios' },
    ],
  },
  {
    id: 'marketing',
    title: 'MARKETING',
    iconName: 'Megaphone',
    path: '/marketing',
    badge: 'ROAS 6.2x',
    badgeColor: 'emerald',
    description: 'Gestão de campanhas, central de anúncios, UTMs, pixels e conversões',
    subItems: [
      { title: 'Dashboard Marketing', path: '/marketing' },
      { title: 'Campanhas', path: '/marketing/campanhas' },
      { title: 'Central de Anúncios', path: '/marketing/anuncios' },
      { title: 'Meta Ads', path: '/marketing/meta-ads' },
      { title: 'Google Ads', path: '/marketing/google-ads' },
      { title: 'TikTok Ads', path: '/marketing/tiktok-ads' },
      { title: 'Spotify Ads', path: '/marketing/spotify-ads' },
      { title: 'Públicos', path: '/marketing/publicos' },
      { title: 'Criativos', path: '/marketing/criativos' },
      { title: 'Cupons', path: '/marketing/cupons' },
      { title: 'Links', path: '/marketing/links' },
      { title: 'UTMs', path: '/marketing/utms' },
      { title: 'QR Codes', path: '/marketing/qrcodes' },
      { title: 'Afiliados', path: '/marketing/afiliados' },
      { title: 'WhatsApp Marketing', path: '/marketing/whatsapp-marketing' },
      { title: 'E-mail Marketing', path: '/marketing/email-marketing' },
      { title: 'Pixels', path: '/marketing/pixels' },
      { title: 'Conversões', path: '/marketing/conversoes' },
      { title: 'Analytics', path: '/marketing/analytics' },
      { title: 'ROAS', path: '/marketing/roas' },
      { title: 'CPA', path: '/marketing/cpa' },
      { title: 'Funil', path: '/marketing/funil' },
      { title: 'Orçamento', path: '/marketing/orcamento' },
      { title: 'Relatórios', path: '/marketing/relatorios' },
    ],
  },
  {
    id: 'remarketing',
    title: 'REMARKETING',
    iconName: 'Repeat',
    path: '/remarketing',
    badge: '28% Recup.',
    badgeColor: 'emerald',
    description: 'Recuperação de carrinhos, audiências segmentadas e jornadas automáticas',
    subItems: [
      { title: 'Dashboard Remarketing', path: '/remarketing' },
      { title: 'Públicos', path: '/remarketing/publicos' },
      { title: 'Segmentos', path: '/remarketing/segmentos' },
      { title: 'Carrinhos Abandonados', path: '/remarketing/carrinhos-abandonados', badge: '142', badgeColor: 'amber' },
      { title: 'Visitantes sem Compra', path: '/remarketing/visitantes-sem-compra' },
      { title: 'Compradores', path: '/remarketing/compradores' },
      { title: 'Clientes Recorrentes', path: '/remarketing/clientes-recorrentes' },
      { title: 'Públicos Semelhantes', path: '/remarketing/publicos-semelhantes' },
      { title: 'WhatsApp', path: '/remarketing/whatsapp' },
      { title: 'E-mail', path: '/remarketing/email' },
      { title: 'Push', path: '/remarketing/push' },
      { title: 'Meta', path: '/remarketing/meta' },
      { title: 'Google', path: '/remarketing/google' },
      { title: 'TikTok', path: '/remarketing/tiktok' },
      { title: 'Jornadas', path: '/remarketing/jornadas' },
      { title: 'Automações', path: '/remarketing/automacoes' },
      { title: 'Recuperação', path: '/remarketing/recuperacao' },
      { title: 'Frequência', path: '/remarketing/frequencia' },
      { title: 'Conversões', path: '/remarketing/conversoes' },
      { title: 'Receita Recuperada', path: '/remarketing/receita-recuperada' },
      { title: 'Relatórios', path: '/remarketing/relatorios' },
    ],
  },
]

export const SYSTEM_UTILITY_LINKS = [
  {
    id: 'auditoria',
    title: 'Auditoria & Logs',
    iconName: 'ShieldCheck',
    path: '/auditoria',
  },
  {
    id: 'configuracoes',
    title: 'Configurações Core',
    iconName: 'Settings',
    path: '/configuracoes',
  },
]
